language: android
dist: trusty
android:
  components:
  
  # gradle build tools
  - build-tools-26.1.1
  
  # the SDK version used to compile the project
  - android-26
  
  # components
  - extra-google-m2repository
  - extra-android-m2repository
  
  # Specify at least one system image,
  # if you need to run emulator(s) during your tests
  - sys-img-x86-android-29
  - sys-img-armeabi-v7a-android-17
